### ISSUE TITLE
Searching Manjaro User who have a working PKGBUILD for the others :)

### ISSUE THREAD

**Issue by Azd325** [Azd325/gitkraken#38]
Would be cool if anyone who has a working gitkraken on manajro post hist PKGBUILD to support the others.

**Comment by polarathene** [comment]
As it turns out, Pamac added native AUR support recently, which unlike previous support doesn't permit users to edit their PKGBUILD... so until that is possible again, not sure how many users will be comfortable doing that. CLI or Octopi of course works :)

I just changed `libcurl-openssl-1.0` to  `libcurl-compat` and it built fine far as I can tell, doesn't run though:

```
❯ gitkraken
ERROR: ld.so: object '/usr/lib/libcurl-openssl-1.0.so.4.4.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Node started time: 1494285201816
/usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /opt/gitkraken/resources/app.asar.unpacked/node_modules/nodegit/build/Release/nodegit.node)
```

I guess the gitkraken.sh might need to be changed too, not sure what the env var `CURL_OPENSSL_3` is meant to contain?

**Comment by marcelloinfoweb** [comment]
Tenho o mesmo problema...

**Comment by KillWolfVlad** [comment]
# Manjaro + GitKraken = :heart:

**ATTENTION! YOU CAN KILL YOUR SYSTEM!**

## Prepare

Install Manjaro on VirtualBox, because you use Arch

## Install `openssl-1.0`

Upgrade your system
```bash
sudo pacman -Syu
```

Download package from [mirror](https://www.archlinux.org/packages/extra/x86_64/openssl-1.0/)

Force install this package
```bash
sudo pacman -U --asdeps --force openssl-1.0-1.0.2.k-3-x86_64.pkg.tar.xz
```

## Install `GitKraken-Pro` (with activated pro features) [recommended]

Download [latest release](https://github.com/KillWolfVlad/GitKraken-Pro-AUR/releases)

Edit `PKGBUILD`
```bash
makedepends=('nodejs>=7.7.3' 'npm>=4.5.0' 'b2t=0.0.0_alpha')
```
Install all dependencies and  build package

## Install `GitKraken` (without pro)

```bash
yaourt -S gitkraken
```

**Comment by MarcinWieczorek** [comment]
You can list libraries with `ldd`. It should help. Use pkgfile too. I'll install Manjaro in a VB tomorrow and give it a try.

**Comment by adalbertobrant** [comment]
Hi Guys ! Have the same problem here , I gonna try to install via debtap.

**Comment by KillWolfVlad** [comment]
@adalbertobrant Try install via `PKGBUILD` with patches from PR #39

**Comment by adalbertobrant** [comment]
Hi , I did try patches from PR #39 ,but did not worked. Here is the printscreen.
![gitkraken-error](https://cloud.githubusercontent.com/assets/6125981/26028160/2f58b678-380a-11e7-852e-2e6d0f5d9030.png)

**Comment by adalbertobrant** [comment]
I' ve send a message to the gitkraken website , maybe they could help us all.

**Comment by KillWolfVlad** [comment]
@adalbertobrant Excuse me, but I don't understand your steps...(did you edit `PKGBUILD`?)

1) Download [darkside-fix-nodegit](https://github.com/KillWolfVlad/GitKraken-Pro-AUR/archive/darkside-fix-nodegit.zip) branch with latest commit
2) Extract archive
3) `cd` to directory with `PKGBUILD`
4) Call `makepkg` in your terminal
5) Paste full log (as text) after this command

P.S.

> I' ve send a message to the gitkraken website , maybe they could help us all.

They know about this bug, see [this](https://github.com/nodegit/nodegit/issues/1225) issue

**Comment by adalbertobrant** [comment]
Thanks @KillWolfVlad

**Comment by polarathene** [comment]
Install the [libcurl-openssl-1.0](https://aur.archlinux.org/packages/libcurl-openssl-1.0/) package from AUR, it'll probably give an error requiring you to add a new gpg key, using the hostname doesn't work so you need to use the IP address as mentioned in the package comments:

Run in terminal(f12 if on Manjaro KDE):
```
gpg --recv-keys --keyserver hkp://18.9.60.141 5CC908FDB71E12C2 
```

Then install the AUR package, once that's done you should be able to install GitKraken from AUR just fine.

Information why GitKraken(or rather a dependency it includes already built) doesn't work well with newer SSL seems to be discussed [here](https://github.com/nodegit/nodegit/issues/1225)

Another option could be to include a flatpak version if possible?

**Comment by KillWolfVlad** [comment]
@polarathene you are right! GitKraken use build-in nodegit with old libcurl version. The best way - rebuild nodegit, see PR #39 

I can't create flatpack packages, but I try it (only for [pro version](https://github.com/KillWolfVlad/GitKraken-Pro-AUR))!

**Comment by polarathene** [comment]
@KillWolfVlad 

> And, why you don't want use tar.gz version?

I am using AUR package for convenience. I think I used tar.gz before the AUR package was available.

The solution I provided is the "best" way for me, does not require me to diverge from how this repos AUR package is provided. I'd rather not do many more steps like you propose.

**Comment by KillWolfVlad** [comment]
@polarathene 

> I am using AUR package for convenience. I think I used tar.gz before the AUR package was available.

I use `PKGBUILD` too. I mean, why you need `flatpak` package and what difference between `flatpak` and `tar.gz`?

> The solution I provided is the "best" way for me, does not require me to diverge from how this repos AUR package is provided. I'd rather not do many more steps like you propose.

Maybe, but I want use default `libcurl`.

**Comment by polarathene** [comment]
@KillWolfVlad 
> I use PKGBUILD too. I mean, why you need flatpak package and what difference between flatpak and tar.gz?

I don't know, why not just offer the tar.gz as a package I guess? Flatpak has some benefits, over tar.gz I guess it can have common layers split out into dependencies to share with other apps packaged with Flatpak, such as GTK/Qt. One benefit for Flatpak over native at least for KDE is you can use a native file dialog instead of the GTK2(soon GTK3 when using an electron build that uses the GTK3 by default that recent Chrome introduce?). 

I do remember when using tar.gz there were some issues/bugs where it would break visually often, but this could have just been due to early days of GitKraken. Flatpak may also have some problems with certain apps due to sandboxing, not sure if  GitKraken is a good app to package for it due to that if it restricts where your repos can be cloned to.

> Maybe, but I want use default libcurl.

That's good, go for it :) For me I just install the extra AUR package once, then GitKraken AUR will update just fine each time and I don't have to tamper with anything with each update.

**Comment by KillWolfVlad** [comment]
@polarathene 

In general - `flatpak` package is very interesting and controversial question

I think `flatpak` can be useful for other distributions (e.g. Fedora)

**Comment by polarathene** [comment]
Slight update, my approach might not be working. Pretty much everything with GitKraken works fine no problems. Just tried to do a push to one of my repos and it's failing. Removed authentication and connected my github account again, generated a new SSH key, still fails to reach Github.

Cloning a repo is fine. So I guess I might have to take @KillWolfVlad approach until Arch packages have better luck with their current rebuild efforts or nodegit figures out how to support the various distros with different versions of openssl in their builds?

**Comment by KillWolfVlad** [comment]
All [Manjaro](https://manjaro.org/) users can try [GitKraken-Pro-AUR](https://github.com/KillWolfVlad/GitKraken-Pro-AUR) latest release

It works perfectly without extra dependencies

**Comment by KillWolfVlad** [comment]
Everybody can try PR #39
